[package]
name = "dioxus-blog"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.5.1", features = ["web", "router"] }
dioxus-router = "0.5.0"
dioxus-web = "0.5.1"
log = "0.4.21"
manganis = "0.2.2"
wasm-logger = "0.2.0"
