[application]
name = "dioxus-blog"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "dioxus-blog"

[web.watcher]
reload_html = false
index_on_404 = true
watch_path = ["src", "public"]

[web.resource]
style = []
script = []

[web.resource.dev]
style = []
script = []
